# Generated by Django 3.1.dev20200417182300 on 2020-04-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetails',
            old_name='phone_number',
            new_name='phone_number',
        ),
    ]
